# ============================================================
# mevoyez Clash Config v1.0
# Clash Verge Rev
# ============================================================


mixed-port: 7890


allow-lan: true


bind-address: "*"


mode: rule


log-level: info


ipv6: false


unified-delay: true


tcp-concurrent: true



# ============================================================
# 控制面板
# ============================================================

external-controller: 127.0.0.1:9090



# ============================================================
# 配置保存
# ============================================================

profile:

  store-selected: true

  store-fake-ip: true



# ============================================================
# 基础代理
# Script 会自动修改
# ============================================================

proxies: []



proxy-groups: []



rule-providers: {}



rules: []



# ============================================================
# DNS
# Script 会覆盖
# ============================================================

dns:

  enable: true

  ipv6: false



# ============================================================
# 嗅探
# ============================================================

sniffer:

  enable: true

  sniff:

    TLS:

      ports:

        - 443

        - 8443


    HTTP:

      ports:

        - 80

        - 8080



# ============================================================
# TUN
# 默认关闭
# ============================================================

tun:

  enable: false
